AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/**'
    - 'app/helpers/**'
    - 'vendor/**/*'

Style/Next:
  Enabled: false

Style/RedundantReturn:
  Enabled: false