default: &default
  adapter: postgresql
  host: "localhost"
  database: "hotel_manager"
  port: 5432
  username: "admin"
  password: "admin"
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  host: "localhost"
  database: "hotel_manager_test"
  port: 5432
  username: "admin"
  password: "admin"
  pool: 5
  timeout: 5000

development:
  <<: *default
test:
  <<: *test
production:
  <<: *default
