default: &default
  adapter: postgresql
  host: "ec2-54-75-233-106.eu-west-1.compute.amazonaws.com"
  database: "d9ndb5elejmegl"
  port: 5432
  username: "flpywsvzvejspd"
  password: "gGMJzo6QgzAL51WUoUp5W0el2R"
  pool: 5
  timeout: 5000

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
